### ISSUE TITLE
Feature request: Include nested version of some tidyr functions

### ISSUE THREAD

**Issue by joranE** [markjrieke/nplyr#13]
Some common data wrangling tools that are used in dplyr-like pipe chains live in tidyr, rather than dplyr. Some would be fairly simple to create "nested" versions, since in general it seems you are just wrapping `mutate()` and `map()`. For example, these would be pretty straightforward I think:

- `fill`
- `replace_na`
- `separate`
- `extract`
- `unite`
- `drop_na`

Things like `pivot_longer` & `pivot_wider` would also be possible, but maybe more complicated. `chop`/`unchop` and `pack`/`unpack` would also be possible, but those are less mature.

I think most of this would be useful, and probably fairly easy, if you think it belongs in this package, rather than maybe being better placed in a separate "nested" tidyr package.

**Comment by markjrieke** [comment]
I think you're right - most of these would be fairly easy to implement since the package currently just wraps dplyr functions in a call to map. Let me noodle on this one for a bit - the package was originally just setup around dplyr specifically, but like you mention a lot of the functions in tidyr are part of typical piped data wrangling workflows
